version: '3.1'

services:
  myapp_db:
    image: postgres:11
    container_name: myapp-db
    #restart: unless-stopped
    environment:
     - POSTGRES_DB=dbname
     - POSTGRES_USER=dbuser
     - POSTGRES_PASSWORD=dbpassword
    ports:
     - "5432:5432"
    volumes:
     - ./data/postgres:/var/lib/postgresql/data

