#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

import pandas as pd
import numpy as np

FNAME='data/foo.csv'

if __name__ == "__main__":

    from numpy.random import randn
    np.random.seed(101)

    df = pd.DataFrame(
        randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()
    )

    df.to_csv(FNAME, index=False)

    print(f'{FNAME} written!')
